services:
  db:
    image: registry.hub.docker.com/library/mysql:lts
    restart: unless-stopped
    env_file: "db.env"
    environment:
      MYSQL_DATABASE: website
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - matiix310-dev-db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    image: registry.hub.docker.com/matiix310/matiix310-dev-api
    build:
      context: ../api/
      dockerfile: ../api/Dockerfile
      target: release
    env_file: "api.env"
    restart: unless-stopped
    networks:
      - matiix310-dev-db
      - matiix310-dev-proxy
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - downloads:/usr/downloads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 5s
      timeout: 5s
      retries: 3

  frontend:
    image: registry.hub.docker.com/matiix310/matiix310-dev-frontend
    build:
      context: ../frontend/
      dockerfile: ../frontend/Dockerfile
      target: release
    restart: unless-stopped
    networks:
      - matiix310-dev-proxy
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/health",
        ]
      interval: 5s
      timeout: 5s
      retries: 3

  reverse-proxy:
    image: registry.hub.docker.com/library/nginx
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      frontend:
        condition: service_healthy
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - matiix310-dev-proxy

volumes:
  downloads:
  mysql:

networks:
  matiix310-dev-db:
  matiix310-dev-proxy:
