events {
    worker_connections          2000;

    # use [ kqueue | epoll | /dev/poll | select | poll ];
    use epoll;
}


http {
    server {
        listen                  80;

        location /api/ {
            proxy_pass          http://api:8000/api/;
        }

        location / {
            proxy_pass          http://frontend:3000/;
        }
    }
}
