events {
    worker_connections          2000;

    # use [ kqueue | epoll | /dev/poll | select | poll ];
    use epoll;
}


http {
    # Made to be behind a cloudflare proxy
    log_format combined_realip_cf '$http_cf_connecting_ip - $remote_user [$time_local] '
                    '"$request" $status $body_bytes_sent '
                    '"$http_referer" "$http_user_agent"';

    access_log /dev/stdout combined_realip_cf;

    server {
        listen                  80;

        location /api/ {
            proxy_pass          http://api:8000/api/;
        }

        location / {
            proxy_pass          http://frontend:3000/;
        }
    }
}
